Controllers/SiteLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Umbraco.Web.Mvc;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;

namespace Firstrand.Controllers
{
    public class SiteLayoutController : SurfaceController
    {
            private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/Layouts/";

            // Top Layout
            public ActionResult RenderTop()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_head.cshtml");
            }

            // Top Layout
            public ActionResult RenderBanner()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_banner.cshtml");
            }

            // SVG Logo
             public ActionResult RenderLogo()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_logo.svg");
            }
            // Site Menu (Top)
            public ActionResult RenderTopMenu()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_top_menu.cshtml");
            }

            // Header Layout
            public ActionResult RenderHeader()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_header.cshtml");
            }

            // Breadrumb Layout
            public ActionResult RenderBreadcrumb()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_breadcrumb.cshtml");
            }

            // Render the page banner
            public ActionResult RenderPageBanner()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_banner.cshtml");
            }

   
            // Footer Layout
            public ActionResult RenderFooter()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_footer.cshtml");
            }

            // Bottom Layout
            public ActionResult RenderBottom()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_bottom.cshtml");
            }

            // Bottom Layout
            public ActionResult RenderGalleryModal()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_GalleryModal.cshtml");
            }

            // Painting Classrooms Menu
            public ActionResult RenderPaintingClassroomsMenu()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_painting_classrooms_menu.cshtml");
            }
            // Painting Classrooms Menu
            public ActionResult RenderOperatingFranchises()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_operating_franchises.cshtml");
            }
            // Scholarships ticker share bar
            public ActionResult RenderTickerShare()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_tickershare.cshtml");
            }
            // Render the scholarships banner
            public ActionResult RenderScholarshipsBanner()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_banner_scholarships.cshtml");
            }
            // Render the website sidebar
            public ActionResult RenderSidebar()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_sidebar.cshtml");
            }

            // Render the cookies disclaimer html template where required
            public ActionResult RenderCookiesDisclaimer()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_disclaimer.cshtml");
            }

            // Render the cookies disclaimer html template where required
            public ActionResult RenderInvestorSidebar()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "/sidebar/investors-sidebar.cshtml");
            }
        }
    }

Controllers/SocietyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;


namespace Firstrand.Controllers
{
    public class SocietyController : SurfaceController
    {
        // Define the route for the partials
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/Society/";

        // Render Investor presentations
        public ActionResult RenderSocialInvesting(){
            return PartialView(PARTIAL_VIEW_FOLDER + "_page_social_investing.cshtml");
        }
        // Render Monitoring and evaluations
        public ActionResult RenderMonitoringEvaluations(){
            return PartialView(PARTIAL_VIEW_FOLDER + "_loop_monitoring_and_evaluation.cshtml");
        }
        // Render Firstrand Foundations
        public ActionResult RenderFirstrandFoundations(){
            return PartialView(PARTIAL_VIEW_FOLDER + "_firstrand_foundations.cshtml");
        }
        // Render Firstrand Empowerment fund
        public ActionResult RenderEmpowermentFund(){
            return PartialView(PARTIAL_VIEW_FOLDER + "_empowerment_fund.cshtml");
        }

        // Render Staff assistance trust
        public ActionResult RenderStaffAssistanceTrust()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_staff_assistance_trust.cshtml");
        }

        // Render the _scholarship_applications partial
        public ActionResult RenderMonitoringAndEvaluation(){
            return PartialView(PARTIAL_VIEW_FOLDER + "_loop_monitoring_and_evaluation.cshtml");
        }
        // Render the scholarships index page
        public ActionResult RenderScholarshipsIndex(){
            return PartialView(PARTIAL_VIEW_FOLDER + "_page_scholarships_index.cshtml");
        }
        // Render the firstrand Volunteers gallery
        public ActionResult RenderFirstrandVolunteers()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_page_firstrand_volunteers.cshtml");
        }
        // Render the firstrand Volunteers single galleries
        public ActionResult RenderSingleGallery()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_loop_galleries.cshtml");
        }


        // Render the firstrand Volunteers single galleries
        public ActionResult RenderPresentations()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "/investors/_loop_presentations.cshtml");
        }
    }
} 

Views/404Page.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Archetype.Extensions;

@*// This template is for the contact page *@


@{
    Layout = null;
}

@{Html.RenderAction("RenderTop", "SiteLayout");}
@{Html.RenderAction("RenderTopMenu", "SiteLayout");}


<div>
    <span>Testing</span>
</div>
   


@{Html.RenderAction("RenderFooter", "SiteLayout");}
@{Html.RenderAction("RenderBottom", "SiteLayout");}

Views/404PageTemp.cshtml
 @inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Archetype.Extensions;

@*// This template is for the contact page *@


@{
    Layout = "WebBase.cshtml";
}

Views/Investors.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Firstrand.Controllers;
@using Firstrand.Models;
@using Archetype.Models;
@using Archetype.Extensions;
@{
    Layout = "WebBase.cshtml";
}

<!-- Defining page aliases -->
@{
    if (CurrentPage.HasValue("contentGrid"))
        {
            @CurrentPage.GetPropertyValue("contentGrid")
        }
    }
@{
    var investor_information = Umbraco.Content(2278);
    var financial_results = Umbraco.Content(2299);

    var interim_result_index = Umbraco.Content(1549);
    var year_end_result_index = Umbraco.Content(1553);

    var social_investing = Umbraco.Content(2015);
    var investor_presentations_index = Umbraco.Content(1715);
    var circulors_index = Umbraco.Content(1716);

    var annual_integrated_reporting_index = Umbraco.Content(2388);

    var disclosures_index = Umbraco.Content(1576);
    var report_to_society_index = Umbraco.Content(1566);
    var governance_compliance_index = Umbraco.Content(1588);
    var securitisations_index = Umbraco.Content(1608);
    var environmental_Index = Umbraco.Content(1587);
    var prospectus_index = Umbraco.Content(1598);

    var share_price = Umbraco.Content(1714);
    var key_facts_and_important_dates = Umbraco.Content(1578);
    var credit_ratings = Umbraco.Content(1593);
    var debt_programmes = Umbraco.Content(1604);
    var credit_counterparty = Umbraco.Content(1592);
    var listed_instruments = Umbraco.Content(1603);

    // Render social investing
    if (CurrentPage.IsEqual(social_investing))
    {
        Html.RenderAction("RenderSocialInvesting", "Investors");
    }
    // Render invetor presentations
    else if (CurrentPage.IsEqual(credit_ratings))
    {
        Html.RenderAction("RenderCreditRatings", "Investors");
        Html.RenderAction("RenderCookiesDisclaimer", "SiteLayout");
    }

    else if (CurrentPage.IsEqual(investor_information))
    {
        Html.RenderAction("RenderPresentations", "Investors");
    }

    else if (CurrentPage.IsEqual(financial_results))
    {
        Html.RenderAction("RenderInterimResults", "Investors");
    }

    else if (CurrentPage.IsEqual(annual_integrated_reporting_index))
    {
        Html.RenderAction("RenderAnnualIntegratedReport", "Investors");
    }

    else if (CurrentPage.IsEqual(governance_compliance_index))
    {
        Html.RenderAction("RenderGovernanceCompliance", "Investors");
    }

    else if (CurrentPage.IsEqual(debt_programmes))
    {
        Html.RenderAction("RenderDebtProgrammes", "Investors");
        Html.RenderAction("RenderCookiesDisclaimer", "SiteLayout");
    }

    //else if (CurrentPage.IsEqual(financial_results))
    //{
    //    Html.RenderAction("RenderYearEndResult", "Investors");
    //}

    //else if (CurrentPage.IsEqual(circulors_index))
    //{
    //    Html.RenderAction("RenderCirculars", "Investors");
    //}
    //else if (CurrentPage.IsEqual(disclosures_index))
    //{
    //    Html.RenderAction("RenderDisclosures", "Investors");
    //}
    //else if (CurrentPage.IsEqual(report_to_society_index))
    //{
    //    Html.RenderAction("RenderReportToSociety", "Investors");
    //}
    //else if (CurrentPage.IsEqual(securitisations_index))
    //{
    //    Html.RenderAction("RenderSecuritisations", "Investors");
    //    Html.RenderAction("RenderCookiesDisclaimer", "SiteLayout");

    //}
    //else if (CurrentPage.IsEqual(environmental_Index))
    //{
    //    Html.RenderAction("RenderEnvironmentals", "Investors");
    //}
    //else if (CurrentPage.IsEqual(prospectus_index))
    //{
    //    Html.RenderAction("RenderProspectuses", "Investors");
    //    Html.RenderAction("RenderCookiesDisclaimer", "SiteLayout");
    //}
    //else if (CurrentPage.IsEqual(interim_result_index))
    //{
    //    Html.RenderAction("RenderInterimResults", "Investors");
    //}
    //else if (CurrentPage.IsEqual(year_end_result_index))
    //{
    //    Html.RenderAction("RenderYearEndResult", "Investors");
    //}
    //else if (CurrentPage.IsEqual(share_price))
    //{
    //    Html.RenderAction("RenderSharePrice", "Investors");
    //}
    //else if (CurrentPage.IsEqual(key_facts_and_important_dates))
    //{
    //    Html.RenderAction("RenderKey_facts_and_important_dates", "Investors");
    //}

    //else if (CurrentPage.IsEqual(credit_counterparty))
    //{
    //    Html.RenderAction("RenderCookiesDisclaimer", "SiteLayout");
    //}
    //else if (CurrentPage.IsEqual(listed_instruments))
    //{
    //    Html.RenderAction("RenderCookiesDisclaimer", "SiteLayout");
    //}
}

Views/MacroPartials/Reports.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
					  asdfasdf

Views/MacroPartials/_Conference.cshtml
<div class="circle-holder-yellow-class">
    <a href="http://firstrand.onlinereport.co.za/test2018/documents/pdfs/BPC_Conference_Concept.pdf" target="_blank">
        <div class="circle-yellow">
            <div class="circle-yellow-sub class-circle1">
                <h5 class="bigger-h5 wow fadeIn" data-wow-duration="0.5s" data-wow-delay="0.5s">
                    <span>
                        Conference
                        concept
                    </span>
                </h5>
            </div>
        </div>
    </a>
    <a href="../2017-conference/conference-photos/">
        <div class="circle-yellow">
            <div class="circle-yellow-sub  class-circle2">
                <h5 class="bigger-h5 wow fadeIn" data-wow-duration="0.5s" data-wow-delay="0.5s">
                    <span>
                        Conference
                        photos
                    </span>
                </h5>
            </div>
        </div>
    </a>
    <a href="../conference-presentations/">
        <div class="circle-yellow">
            <div class="circle-yellow-sub  class-circle3">
                <h5 class="bigger-h5 wow fadeIn" data-wow-duration="0.5s" data-wow-delay="0.5s">
                    <span>
                        Conference
                        presentations
                    </span>
                </h5>
            </div>
        </div>
    </a>
    <a href="http://firstrand.onlinereport.co.za/test2018/documents/pdfs/BPC_Conference_Concept.pdf" target="_blank">
        <div class="circle-yellow">
            <div class="circle-yellow-sub  class-circle4">
                <h5 class="bigger-h5 wow fadeIn" data-wow-duration="0.5s" data-wow-delay="0.5s">
                    <span>
                        Post
                        conference
                        task
                    </span>
                </h5>
            </div>
        </div>
    </a>
</div>

Views/MacroPartials/_ConferencePresentation.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
<div class="full-div">
    <div class="full-div">
         <button type="button" class="btn landing-btn-primary ivestor-btn ivestor-btn-active" id="monthly1">
            DAY 1 <i class="fa fa-arrow-circle-right" aria-hidden="true"></i></button>
        <button type="button" class="btn landing-btn-primary ivestor-btn" id="monthly2">
            DAY 2 <i class="fa fa-arrow-circle-right" aria-hidden="true"></i></button>
    </div>
    <div class="full-div" id="disclosure1" style="display: block;">
        <div class="col-md-8">
            <div class="boxed-classroom">
                <div class="class-links">
                   @{
                    var selection = Umbraco.TypedContent(1484).Children("workshopPresentation")
                    .Where(x => x.IsVisible()).OrderBy("UpdateDate desc");
                    }
                    @foreach(var item in selection){
                    <a href="/media/1056/download.pdf" target="_blank"><img src="/images/pdf_icon.png" alt="">@item.Name</a>
                    }
                </div>
            </div>
        </div>
    </div>

     <div class="full-div" id="disclosure2" style="display: none;">
        <div class="col-md-8">
            <div class="boxed-classroom">
                <div class="class-links">
                    <a href=""><img src="../../../images/pdf_icon.png" alt="">Lindiwe and Frank - George Khosa Secondary
                        School</a>
                </div>
            </div>
        </div>
    </div>
</div>

Views/MacroPartials/_Conference_photos.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
    var typedMultiMediaPicker = Model.Content.GetPropertyValue<IEnumerable<IPublishedContent>>("conferenceGallery"); 
        var i = 0;
        foreach (var item in typedMultiMediaPicker)
        {
          i++;
            <div class="">
                <div class="gallery-img-div">
                    <a href="@item.Url">
                        <img src="@item.Url"
                            class="img-responsive "
                            style="margin-bottom: 15px;" />
                    </a>
    			</div>
            </div>
            if (i % 5 == 0){
                <div class="clearfix"></div>
                 }
        }
}

Views/MacroPartials/_In_the_news.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
<div class="full-div">
    <div class="col-md-8">
        <div class="full-div boxed-classroom">
            <div class="class-links">
              
                @{
                    var selection = Model.Content.Site().FirstChild("society").FirstChild("societyPage").FirstChild("paintingClassrooms").FirstChild("newsItemsList").Children("newsItems").Where(x => x.IsVisible()).OrderBy("UpdateDate desc");
                }
                @foreach (var item in selection)
                {
                    <a href="/media/1056/download.pdf" target="_blank"><img src="/images/pdf_icon.png" alt="">@item.Name</a>
                }
            </div>
        </div>
    </div>
</div>

Views/MacroPartials/_Presentations.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
<div class="full-div">
    <div class="col-md-8">
        <div class="boxed-classroom">
            <div class="class-links">
                @{
                var selection = Umbraco.TypedContent(1332).Children("workshopPresentation").Where(x => x.IsVisible()).OrderBy("UpdateDate desc");
                }
                @foreach (var item in selection)
                {

                <a href="@item.GetPropertyValue("uploadField")"><img src="/images/pdf_icon.png" alt="">@item.Name</a>
                }
            </div>
        </div>
    </div>
</div>

Views/MacroPartials/_SENS.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="sens" id="demo"></div>
    </div>
    <!--<div class="tab-pane fade" id="tab2danger">-->
    <!--<div class="sens" id="demo1"></div>-->
    <!--</div>-->
    <!--<div class="tab-pane fade" id="tab3danger">-->
    <!--<div class="sens" id="demo2"></div>-->
    <!--</div>-->
    <script>
                            function loadXMLDoc() {
                                var xmlhttp = new XMLHttpRequest();
                                xmlhttp.onreadystatechange = function () {
                                    if (this.readyState == 4 && this.status == 200) {
                                        myFunctions(this);
                                    }
                                };
                                xmlhttp.open("GET", "https://irhosted.profiledata.co.za/firstrand/sens.xml", true);
                                xmlhttp.send();
                            }
                            function myFunctions(xml) {
                                var i;
                                var xmlDoc = xml.responseXML;
                                var table = "";
                                var x = xmlDoc.getElementsByTagName("Headline");
                                for (i = 0; i < x.length; i++) {
                                    table += "<a href='" +
                                            x[i].getElementsByTagName("Link")[0].childNodes[0].nodeValue + "' target='_blank'> <div class='sens-box'><div class='sens-date'>" +
                                            x[i].getElementsByTagName("PubDate")[0].childNodes[0].nodeValue +
                                            "</div><div class='sens-name'>" +
                                            x[i].getElementsByTagName("HeadlineText")[0].childNodes[0].nodeValue +
                                            "</div></div></a>";
                                }
                                document.getElementById("demo").innerHTML = table;
                                document.getElementById("demo1").innerHTML = table;
                                document.getElementById("demo2").innerHTML = table;
                            }

                            loadXMLDoc();
    </script>
</div>

Views/MacroPartials/_Workshop.cshtml
<div class="boxed-classroom">
							<div class="col-md-4">
							<a href="../../../documents/pdfs/beyond-painting-classroom/BPC_Aligning_EV_with_Core_Business_Strategy-29_October_2014.pdf" target="_blank"><img src="../../../images/BPC_cover5.jpg" alt="">BPC Aligning EV with Core
Business Strategy - 29
October 2014</a>
								</div>
								<div class="col-md-4">
								<a href="../../../documents/pdfs/beyond-painting-classroom/BPC_Skills-Based_Volunteering_Workshop-11th_June_2014.pdf" target="_parent"><img src="../../../images/BPC_cover11.jpg" alt="">BPC Skills-Based
Volunteering Workshop - 11th
June 2014</a>
								</div>
								<div class="col-md-4">
									<a href="../../../documents/pdfs/beyond-painting-classroom/BPC_Skills-based_Volunteering_Workshop_Report–5th_March_2014.pdf" target="_parent"><img src="../../../images/BPC_cover29.jpg" alt="">BPC Skills-based Volunteering
Workshop Report – 5th
March 2014</a>
								</div>
							  </div>
		

Views/MacroPartials/_group-strategic-framework.cshtml
<div class="group-strategy">
    <div class="section-heading wow fadeIn">
        <h2 class="heading">
            <span> group </span> strategy
        </h2>

        <p class="lead">
            As demonstrated in the schematic below, the group's strategic framework accommodates a broad
            set of growth opportunities across the financial services universe from <strong>
                a product,
                market,
                segment and geographic perspective.
            </strong>
        </p>

        <h3>
            Group strategic framework
        </h3>

        <div class="card mb-2 border-none text-center">
            <p class="card-header">
                FirstRand aims to create long-term franchise value, ensure sustainable and superior returns
                for
                shareholders within acceptable levels of volatility and maintain balance sheet strength
            </p>
        </div>

        <div class=" row gray-and-white-block__small_divice mb-5">
            <img src="../images/framework.jpg" class="img-fluid" />
        </div>
        <div class="Gray-block wow fadeIn">
            <div class="row">
                <div class="col-md-3">
                </div>
                <div class="col-md-9">
                    <div class="header-text">Delivered through current strategies:</div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <div class="white-block-black first-white-block">
                        <br><span>Protect and grow</span> <br>banking franchises<br>&nbsp;
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="block-dotted-line">
                        <div class="header-text">Increase DIVERSIFICATION - activity and geography</div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="white-block-black">
                                    <span>Broaden</span> financial<br> services
                                    <span>offering</span>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="white-block-black">
                                    <span>Portfolio</span> approach <br>to <span>rest of Africa</span>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="white-block-black">
                                    Build a <span>sustainable UK<br> business</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom-block-white">
            <div class="row">
                <div class="col-md-6">
                    <div class="white-block-black-line group-squareline1"></div><br>
                    
                    <div class="country-block-head">SOUTH AFRICA</div>
                    <img src="~/images/arrow-down.png" class="arrow__1" />
                    <div class="country-block-text">Build a truly integrated <br> financial services business</div>
                </div>
                <div class="col-md-3">
                    <div class="white-block-black-line group-squareline2"></div><br>
                       <img src="~/images/arrow-down.png" class="arrow__2" />
                    <div class="country-block-head">REST OF AFRICA</div>
                    <div class="country-block-text">Better leverage <br>existing portfolio</div>
                </div>
                <div class="col-md-3">
                    <div class="white-block-black-line group-squareline3"></div><br>
                    <div class="country-block-head">UK</div>
                       <img src="~/images/arrow-down.png" class="arrow__3" />
                    <div class="country-block-text">Integrate, <br> scale and grow</div>
                </div>
            </div>
        </div>

        

            <div class="card mb-2 size_f">
                <div class="card-body text-center p-2 ">
                    <strong><p class="mb-0">Underpinned by disciplined management of financial resources</p></strong>
                </div>
            </div>
            <div class="card  size_f">
                <div class="card-body text-center p-2">
                    <strong><p class="mb-0">Enabled by disruptive digital and data platforms</p></strong>
                </div>
           
        </div>

       
    </div>
  
</div>

Views/Pages.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
}

@{
    @{
        if (CurrentPage.HasValue("contentGrid"))
        {
            @CurrentPage.GetPropertyValue("contentGrid")
        }
    }

Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@Html.Raw(Model.value)

Views/SocietyPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Firstrand.Controllers;
@using Firstrand.Models;
@using Archetype.Models;
@using Archetype.Extensions;
@{
    Layout = "WebBase.cshtml";
}
@{
    if (CurrentPage.HasValue("contentGrid"))
    {
        @CurrentPage.GetPropertyValue("contentGrid")
    }
}

@{
    var page_social_investing = Umbraco.Content(2015);
    var firstrand_foundations = Umbraco.Content(1689);
    var empowerment_fund = Umbraco.Content(1690);
    var monitoring_and_evaluation = Umbraco.Content(1744);
    var scholarships_index = Umbraco.Content(1698);
    var firstrand_volunteers = Umbraco.Content(1241);
    var staff_assistance_trust = Umbraco.Content(2397);


    if (CurrentPage.IsEqual(page_social_investing))
    {
        Html.RenderAction("RenderSocialInvesting", "Society");
    }
    if (CurrentPage.IsEqual(firstrand_foundations))
    {
        Html.RenderAction("RenderFirstrandFoundations", "Society");
    }
    if (CurrentPage.IsEqual(empowerment_fund))
    {
        Html.RenderAction("RenderEmpowermentFund", "Society");
    }
    if (CurrentPage.IsEqual(monitoring_and_evaluation))
    {
        Html.RenderAction("RenderMonitoringAndEvaluation", "Society");
    }

    //if (CurrentPage.IsEqual(staff_assistance_trust))
    //{
    //    Html.RenderAction("RenderStaffAssistanceTrust", "Society");
    //}

    //if (CurrentPage.IsEqual(scholarships_index))
    //{
    //    Html.RenderAction("RenderScholarshipsIndex", "Society");
    //}

    if (CurrentPage.IsEqual(firstrand_volunteers))
    {
        Html.RenderAction("RenderFirstrandVolunteers", "Society");
    }


}

@{ if (@CurrentPage.DocumentTypeAlias == "singleGallery")
    {
    }
}

Views/webBaseContact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Archetype.Extensions;

@*// This template is for the contact page *@


@{
    Layout = null;
}

@{Html.RenderAction("RenderTop", "SiteLayout");}
@{Html.RenderAction("RenderTopMenu", "SiteLayout");}

<!-- /Heading section -->

<header class="jumbotron">
    <div class="map-frame">

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3582.936851263109!2d28.054171315027972!3d-26.100979983483928!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1e95732f26549b3b%3A0x6976238775857e33!2sFirstRand+Bank+Ltd!5e0!3m2!1sen!2s!4v1508344021503"
                width="100%" height="400" frameborder="0" style="border:0" allowfullscreen=""></iframe>
    </div>
</header>

<!-- Page content -->
<section class="page-content p-0">

    <div class="container-fluid contact p-0">
        <div class="row">

            <div class="col-md-4">

                <img src="/images/icons/email-icon.png" alt="" class="img-fluid" style="width: 20px;">

                <div class="address">


                    <h4>Address:</h4>
                    <ul class="list-unstyled">
                        <li> T-Mobile Customer Relations</li>
                        <li> PO Box 37380</li>
                        <li> Albuquerque, NM 87176-7380</li>
                    </ul>

                    <h4>Address:</h4>
                    <ul class="list-unstyled">
                        <li> T-Mobile Customer Relations</li>
                        <li> PO Box 37380</li>
                        <li> Albuquerque, NM 87176-7380</li>
                    </ul>


                </div>
                

                   
                
            </div>

            <div class="col-md-4">
                <div class="phone">
                    <h5>Phone:</h5>
                    <ul class="list-unstyled">
                        <li> +91- 8800XXXXXX34</li>
                        <li> +91- 8800XXXXXX34</li>
                    </ul>
                </div>
            </div>

            <div class="col-md-4">

                <div class="email">
                    <h5>Email:</h5>
                    <ul class="list-unstyled">
                        <li> info@email.com</li>
                        <li> info@email.com</li>
                    </ul>
                </div>




            </div>



        </div>
    </div>

</section>

@{Html.RenderAction("RenderFooter", "SiteLayout");}
@{Html.RenderAction("RenderBottom", "SiteLayout");}